### ISSUE TITLE
Infinite recursion in uname

### ISSUE THREAD

**Issue by jaraco** [jaraco/cmdix#1]
After creating scripts for the package, I started to run into issues where tests would hang for a very long time during startup.

After some troubleshooting, I stumbled on this process tree, indicating the cause:

```
     \-+= 69252 jaraco /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Library/Frameworks/Python.framework/Versions/3.7/bin/tox -vvv
 | |   \-+- 69297 jaraco /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Users/jaraco/code/main/cmdix/.tox/python/bin/pytest
 | |     \-+- 69302 jaraco /bin/sh -c uname -p 2> /dev/null
 | |       \-+- 69304 jaraco /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Users/jaraco/code/main/cmdix/.tox/python/bin/uname -p
 | |         \-+- 69308 jaraco /bin/sh -c uname -p 2> /dev/null
 | |           \-+- 69309 jaraco /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Users/jaraco/code/main/cmdix/.tox/python/bin/uname -p
 | |             \-+- 69310 jaraco /bin/sh -c uname -p 2> /dev/null
 | |               \-+- 69311 jaraco /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Users/jaraco/code/main/cmdix/.tox/python/bin/uname -p
 | |                 \-+- 69312 jaraco /bin/sh -c uname -p 2> /dev/null
... and so on
```

I'm guessing eventually the recursion hits some system limit causing the `uname` call to crash.

Inspecting the Python source, I can see where [platform.uname actually calls `sh -c uname -p`](https://github.com/python/cpython/blob/9db56fb8faaa3cd66e7fe82740a4ae4d786bb27f/Lib/platform.py#L836). But if `cmdix` is providing a `uname` command and if tox has effectively activated the bin directory of cmdix, the `platform` module will end up calling `cmdix.uname` instead of the system one, which in turn calls `platform.processor()`, which calls `cmdix.uname`... and so on. Yuck.

**Comment by jaraco** [comment]
That didn't fix it... because all _any_ call that goes through `uname()`, including `platform.machine`, `platform.system()`, `platform.node()`, ... still _trigger_ the `_syscmd_uname` invocation. I don't think it's going to be possible to fix this without monkey-patching the stdlib.

**Comment by jaraco** [comment]
I think it's worse than that. Since the cmdix `uname` command is launched by setuptools/pkg_resources, and since pkg_resources probably invokes `platform.something` prior to locating the executable, cmdix has no opportunity to prevent the stdlib from making the recursive call.

**Comment by jaraco** [comment]
I'm confirmed that importing or iterating on entry points does _not_ trigger a call to `platform.uname()`, so it may still be possible to monkeypatch it.

**Comment by jaraco** [comment]
The issue is that during marker evaluation, the platform is invoked... and that happens before any monkeypatching can take place:

```
Traceback (most recent call last):
  File ".tox/python/bin/uname", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2635, in requires
    dm = self._dep_map
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2601, in _dep_map
    self.__dep_map = self._filter_extras(self._build_dep_map())
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2616, in _filter_extras
    invalid_marker(marker)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1358, in invalid_marker
    evaluate_marker(text)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1376, in evaluate_marker
    return marker.evaluate()
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 297, in evaluate
    current_environment = default_environment()
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 261, in default_environment
    "platform_machine": platform.machine(),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/platform.py", line 1104, in machine
    return uname().machine
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/platform.py", line 1033, in uname
    processor = _syscmd_uname('-p', '')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/platform.py", line 791, in _syscmd_uname
    output = f.read().strip()
KeyboardInterrupt
```

**Comment by jaraco** [comment]
It might be possible to avoid the use of pkg_resources if `use_develop` weren't employed for tests.
