### ISSUE TITLE
More is broken

### ISSUE THREAD

**Issue by jaraco** [jaraco/cmdix#4]
```
cmdix main $ .tox/python/bin/more setup.py
Traceback (most recent call last):
  File "/Users/jaraco/code/main/cmdix/.tox/python/bin/more", line 8, in <module>
    sys.exit(run())
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.9/site-packages/cmdix/__init__.py", line 128, in run
    return run_subcommand(commandname, argv)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.9/site-packages/cmdix/__init__.py", line 166, in run_subcommand
    args.func(args)
  File "/Users/jaraco/code/main/cmdix/.tox/python/lib/python3.9/site-packages/cmdix/command/more.py", line 21, in func
    for line, filename in lib.parsefilelist(args.FILE):
ValueError: too many values to unpack (expected 2)
```

**Comment by jaraco** [comment]
sendmail and sort have the same bug
